version: 2.1

orbs: 
  maven: circleci/maven@1.3.0
  docker: circleci/docker@2.0.3

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.2
    steps:
      - setup_remote_docker
      - checkout
      - run: java --version
      - run: mvn --version
      - run: 
          name: Run Maven Package
          command: |
            mvn clean package -P mysql -DskipTests=true
      - run:
          name: Docker Build
          command: |
            docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
      - run:
          name: Docker TAG
          command: |
            docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_REPO/$DOCKER_IMAGE:$DOCKER_TAG
      - run:
          name: Login Docker
          command: |
            docker login -u $DOCKER_USR -p $DOCKER_PASS
      - run:
          name: Push Image Docker
          command: |
            docker push $DOCKER_REPO/$DOCKER_IMAGE:$DOCKER_TAG

